PROJECT_NAME     := led_blink_test
TARGETS          := led_blink_test
OUTPUT_DIRECTORY := build/

SDK_ROOT := ../urf_lib/nrf_usdk52
PROJ_DIR := .

# nRF52840 Dongle - Application at 0x1000 (after MBR)
$(OUTPUT_DIRECTORY)/led_blink_test.out: \
  LINKER_SCRIPT := $(PROJ_DIR)/nrf52840_dongle.ld

# Source files - minimal
SRC_FILES += \
  $(PROJ_DIR)/led_blink_test.c \
  $(SDK_ROOT)/gcc/gcc_startup_nrf52.S \
  $(SDK_ROOT)/system_nrf52.c \

# Include folders
INC_FOLDERS += \
  $(PROJ_DIR) \
  $(SDK_ROOT)/device \
  $(SDK_ROOT)/cmsis/include \
  $(SDK_ROOT) \

# Optimization flags
OPT = -Os

# C flags - Use nRF52832 defines (compatible with nRF52840)
CFLAGS += $(OPT)
CFLAGS += -DBOARD_PCA10059
CFLAGS += -DNRF52832_XXAA
CFLAGS += -DNRF52
CFLAGS += -D__STACK_SIZE=0x800
CFLAGS += -D__HEAP_SIZE=0x200
CFLAGS += -mcpu=cortex-m4
CFLAGS += -mthumb -mabi=aapcs
CFLAGS += -Wall
CFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
CFLAGS += -ffunction-sections -fdata-sections -fno-strict-aliasing
CFLAGS += -fno-builtin -fshort-enums

# Assembler flags
ASMFLAGS += -g3
ASMFLAGS += -mcpu=cortex-m4
ASMFLAGS += -mthumb -mabi=aapcs
ASMFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
ASMFLAGS += -DBOARD_PCA10059
ASMFLAGS += -DNRF52832_XXAA
ASMFLAGS += -DNRF52
ASMFLAGS += -D__STACK_SIZE=0x800
ASMFLAGS += -D__HEAP_SIZE=0x200

# Linker flags
LDFLAGS += $(OPT)
LDFLAGS += -mthumb -mabi=aapcs -L $(TEMPLATE_PATH) -T$(LINKER_SCRIPT)
LDFLAGS += -mcpu=cortex-m4
LDFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
LDFLAGS += -Wl,--gc-sections
LDFLAGS += --specs=nano.specs

LIB_FILES += -lc -lnosys -lm

.PHONY: default

default: led_blink_test

TEMPLATE_PATH := $(SDK_ROOT)/gcc

include $(TEMPLATE_PATH)/Makefile.common

$(foreach target, $(TARGETS), $(call define_target, $(target)))
